const telosController = require('./../controllers/telosController.js')
const express = require('express')
const router = express.Router()
router.get('/', telosController.list)
    //router.get('/:idL', telosController.showByID)
    //router.get('/:idL/:idRooms?', telosController.showByRooms)
    //router.get('/search', telosController.searchByKey)
    //router.get('/newLocal', telosController.create)
    // router.get('/ofertas', telosController.showBySearch)
module.exports = router